### ISSUE TITLE
UI things that need to be made better PLEASSSSEEEE ELYSE :)

### ISSUE THREAD

**Issue by falon3** [CMPUT301F15T15/Team15Alpha#190]
uhhh thumbnails in editSkillActivity... weird gridview problem

edit contact info- functions but looks horrendous because Falon has no clue how to make it nicer

**Comment by FancifulEight** [comment]
Did you just refer to yourself in the third person?
Fanciful thinks she did.

**Comment by FancifulEight** [comment]
Honestly, the order of UI to fix is probably,
- GeneralMenu (search bar)
- Profile (horribly messed up due to inexperienced placing of new UI elements)
- EditSkill (Images are in an iffy place)
  The editskill images might need a list adapter and I am the most experienced with those, so I might do them. I added some new icons in the latest commit, feel free to take a look.
